# Generated by Django 4.2.7 on 2023-12-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=150)),
                ('done', models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], max_length=5)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('termino', models.DateField()),
                ('finalizado_em', models.DateField(null=True)),
            ],
        ),
    ]
