# Generated by Django 4.2.7 on 2023-12-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='finalizado_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
